# Setup services {Django, Nginx, PostgreSQL...}
# specify the version of the docker-compose
version:  "3"

# define the services
services:
  django:
    container_name: django-adminlte
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  redis:
    image: redis:latest
    container_name: redis-adminlte

  celery:
    build: .
    command: celery -A app worker --loglevel=info -E
    container_name: celery-adminlte
    restart: on-failure
    depends_on:
      - redis
  celery-beat:
    build: .
    command: celery -A app beat --loglevel=info
    container_name: celery-beat-adminlte
    restart: on-failure
    depends_on:
      - redis
      - celery
